bucket:
  staging:
    name: "autop-staging"
  raw:
    name: "autop-raw"
  trusted:
    name: "autop-trusted"
  refined:
    name: "autop-refined"
db:
  zoho:
    instance:
      ip: 54.174.251.9
      name: "ec2-autoprovision"
