version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: "1"
    entrypoint: ["sh", "-c", "python main.py"]
    restart: "no"
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 7g
        reservations:
          memory: 6g
    resources:
      mem_limit: 7g
